on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GO_VERSION: '1.21'
jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          verbose: true
  Publishing:
    runs-on: ubuntu-latest
    needs:
      - Dockerfile
      - Go
    steps:
      - uses: actions/checkout@v3
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE }}
          registry: ghcr.io/${{ github.repository_owner }}
      - name: podman build
        run: |
          podman build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: podman push
        run: |
          podman push ghcr.io/${{ github.repository }}:${{ github.sha }}
